export const requisitionsData = [
	{
		id: 1,
		prNumber: 'PR-202511-0010',
		title: 'Office Supplies Q4',
		status: 'Approved',
		priority: 'Normal',
		cataloged: true,
		requiredDate: '2025-11-10',
		costCenter: 'IT-001',
		totalAmount: '$15,420.50',
		createdDate: '2025-11-10',
	},
	{
		id: 2,
		prNumber: 'PR-202511-0011',
		title: 'Office Supplies Q4',
		status: 'Pending',
		priority: 'Normal',
		cataloged: true,
		requiredDate: '2025-11-10',
		costCenter: 'IT-001',
		totalAmount: '$15,420.50',
		createdDate: '2025-11-10',
	},
	{
		id: 3,
		prNumber: 'PR-202511-0012',
		title: 'Office Supplies Q4',
		status: 'Draft',
		priority: 'Normal',
		cataloged: false,
		requiredDate: '2025-11-10',
		costCenter: 'IT-001',
		totalAmount: '$15,420.50',
		createdDate: '2025-11-10',
	},
];

export const catalogItems = [
	{
		id: 1,
		name: 'HP Laptop',
		code: 'LAPTOP-HP',
		price: 1200.0,
		description: 'Default catalog item for receipts without catalog reference',
	},
	{
		id: 2,
		name: 'HP Laptop',
		code: 'LAPTOP-HP',
		price: 1200.0,
		description: 'Default catalog item for receipts without catalog reference',
	},
	{
		id: 3,
		name: 'HP Laptop',
		code: 'LAPTOP-HP',
		price: 1200.0,
		description: 'Default catalog item for receipts without catalog reference',
	},
	{
		id: 4,
		name: 'HP Laptop',
		code: 'LAPTOP-HP',
		price: 1200.0,
		description: 'Default catalog item for receipts without catalog reference',
	},
	{
		id: 5,
		name: 'HP Laptop',
		code: 'LAPTOP-HP',
		price: 1200.0,
		description: 'Default catalog item for receipts without catalog reference',
	},
	{
		id: 6,
		name: 'HP Laptop',
		code: 'LAPTOP-HP',
		price: 1200.0,
		description: 'Default catalog item for receipts without catalog reference',
	},
	{
		id: 7,
		name: 'HP Laptop',
		code: 'LAPTOP-HP',
		price: 1200.0,
		description: 'Default catalog item for receipts without catalog reference',
	},
	{
		id: 8,
		name: 'HP Laptop',
		code: 'LAPTOP-HP',
		price: 1200.0,
		description: 'Default catalog item for receipts without catalog reference',
	},
];
