export const cardNavigationMap = {
	Setup: "/segments",
	Currencies: "/currency",
	Countries: "/countries",
	"Tax Rates": "/tax-rates",
	"Invoice Approvals": "/approvals",
	"Journal Entries": "/journal-entries",
	Customers: "/customers",
	Suppliers: "/Suppliers",
	Reports: "/reports",
	"Accounts Receivable": "/ar-invoices",
	"Accounts Payable": "/ap-invoices",
	"One-Time Supplier Invoices": "/one-time-supplier-invoices",
	"Default Values": "/default-values",
};
